# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonframe = QtWidgets.QFrame(self.centralwidget)
        self.buttonframe.setGeometry(QtCore.QRect(1630, 10, 271, 1011))
        self.buttonframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonframe.setObjectName("buttonframe")
        self.browseButton = QtWidgets.QPushButton(self.buttonframe)
        self.browseButton.setGeometry(QtCore.QRect(20, 10, 21, 23))
        self.browseButton.setObjectName("browseButton")
        self.webcamButton = QtWidgets.QPushButton(self.buttonframe)
        self.webcamButton.setGeometry(QtCore.QRect(70, 10, 75, 23))
        self.webcamButton.setCheckable(True)
        self.webcamButton.setChecked(False)
        self.webcamButton.setAutoRepeat(False)
        self.webcamButton.setDefault(False)
        self.webcamButton.setObjectName("webcamButton")
        self.retinaButton = QtWidgets.QCheckBox(self.buttonframe)
        self.retinaButton.setGeometry(QtCore.QRect(170, 10, 71, 21))
        self.retinaButton.setObjectName("retinaButton")
        self.maintabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.maintabWidget.setGeometry(QtCore.QRect(10, 0, 1611, 1021))
        self.maintabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.maintabWidget.setObjectName("maintabWidget")
        self.mainpage = QtWidgets.QWidget()
        self.mainpage.setObjectName("mainpage")
        self.dataframe = QtWidgets.QFrame(self.mainpage)
        self.dataframe.setGeometry(QtCore.QRect(0, 0, 1611, 1011))
        self.dataframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataframe.setObjectName("dataframe")
        self.videoframe = QtWidgets.QFrame(self.dataframe)
        self.videoframe.setGeometry(QtCore.QRect(10, 0, 1601, 851))
        self.videoframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe.setObjectName("videoframe")
        self.label = QtWidgets.QLabel(self.videoframe)
        self.label.setGeometry(QtCore.QRect(560, 30, 480, 360))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.focallabel = QtWidgets.QLabel(self.videoframe)
        self.focallabel.setGeometry(QtCore.QRect(200, 430, 480, 360))
        self.focallabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.focallabel.setText("")
        self.focallabel.setObjectName("focallabel")
        self.corticallabel = QtWidgets.QLabel(self.videoframe)
        self.corticallabel.setGeometry(QtCore.QRect(930, 430, 480, 360))
        self.corticallabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.corticallabel.setText("")
        self.corticallabel.setObjectName("corticallabel")
        self.scrubframe = QtWidgets.QFrame(self.dataframe)
        self.scrubframe.setGeometry(QtCore.QRect(0, 850, 1611, 161))
        self.scrubframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrubframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe.setObjectName("scrubframe")
        self.scrubSlider = QtWidgets.QSlider(self.scrubframe)
        self.scrubSlider.setGeometry(QtCore.QRect(19, 10, 1531, 22))
        self.scrubSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scrubSlider.setObjectName("scrubSlider")
        self.frameNum = QtWidgets.QLCDNumber(self.scrubframe)
        self.frameNum.setGeometry(QtCore.QRect(1560, 10, 31, 23))
        self.frameNum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameNum.setSmallDecimalPoint(False)
        self.frameNum.setObjectName("frameNum")
        self.pauseButton = QtWidgets.QPushButton(self.scrubframe)
        self.pauseButton.setGeometry(QtCore.QRect(770, 40, 75, 23))
        self.pauseButton.setCheckable(True)
        self.pauseButton.setObjectName("pauseButton")
        self.maintabWidget.addTab(self.mainpage, "")
        self.gallerypage = QtWidgets.QWidget()
        self.gallerypage.setObjectName("gallerypage")
        self.dataframe_2 = QtWidgets.QFrame(self.gallerypage)
        self.dataframe_2.setGeometry(QtCore.QRect(0, 0, 1621, 1011))
        self.dataframe_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataframe_2.setObjectName("dataframe_2")
        self.videoframe_4 = QtWidgets.QFrame(self.dataframe_2)
        self.videoframe_4.setGeometry(QtCore.QRect(10, 0, 1531, 1001))
        self.videoframe_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe_4.setObjectName("videoframe_4")
        self.label0_8 = QtWidgets.QLabel(self.videoframe_4)
        self.label0_8.setGeometry(QtCore.QRect(70, 10, 320, 180))
        self.label0_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label0_8.setText("")
        self.label0_8.setObjectName("label0_8")
        self.label0_9 = QtWidgets.QLabel(self.videoframe_4)
        self.label0_9.setGeometry(QtCore.QRect(420, 10, 320, 180))
        self.label0_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label0_9.setText("")
        self.label0_9.setObjectName("label0_9")
        self.label0_10 = QtWidgets.QLabel(self.videoframe_4)
        self.label0_10.setGeometry(QtCore.QRect(770, 10, 320, 180))
        self.label0_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label0_10.setText("")
        self.label0_10.setObjectName("label0_10")
        self.label0_11 = QtWidgets.QLabel(self.videoframe_4)
        self.label0_11.setGeometry(QtCore.QRect(1120, 10, 320, 180))
        self.label0_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label0_11.setText("")
        self.label0_11.setObjectName("label0_11")
        self.label1_8 = QtWidgets.QLabel(self.videoframe_4)
        self.label1_8.setGeometry(QtCore.QRect(770, 250, 320, 180))
        self.label1_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label1_8.setText("")
        self.label1_8.setObjectName("label1_8")
        self.label1_9 = QtWidgets.QLabel(self.videoframe_4)
        self.label1_9.setGeometry(QtCore.QRect(1120, 250, 320, 180))
        self.label1_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label1_9.setText("")
        self.label1_9.setObjectName("label1_9")
        self.label1_10 = QtWidgets.QLabel(self.videoframe_4)
        self.label1_10.setGeometry(QtCore.QRect(70, 250, 320, 180))
        self.label1_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label1_10.setText("")
        self.label1_10.setObjectName("label1_10")
        self.label1_11 = QtWidgets.QLabel(self.videoframe_4)
        self.label1_11.setGeometry(QtCore.QRect(420, 250, 320, 180))
        self.label1_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label1_11.setText("")
        self.label1_11.setObjectName("label1_11")
        self.label2_8 = QtWidgets.QLabel(self.videoframe_4)
        self.label2_8.setGeometry(QtCore.QRect(1120, 490, 320, 180))
        self.label2_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label2_8.setText("")
        self.label2_8.setObjectName("label2_8")
        self.label2_9 = QtWidgets.QLabel(self.videoframe_4)
        self.label2_9.setGeometry(QtCore.QRect(70, 490, 320, 180))
        self.label2_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label2_9.setText("")
        self.label2_9.setObjectName("label2_9")
        self.label2_10 = QtWidgets.QLabel(self.videoframe_4)
        self.label2_10.setGeometry(QtCore.QRect(770, 490, 320, 180))
        self.label2_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label2_10.setText("")
        self.label2_10.setObjectName("label2_10")
        self.label2_11 = QtWidgets.QLabel(self.videoframe_4)
        self.label2_11.setGeometry(QtCore.QRect(420, 490, 320, 180))
        self.label2_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label2_11.setText("")
        self.label2_11.setObjectName("label2_11")
        self.label3_8 = QtWidgets.QLabel(self.videoframe_4)
        self.label3_8.setGeometry(QtCore.QRect(770, 730, 320, 180))
        self.label3_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label3_8.setText("")
        self.label3_8.setObjectName("label3_8")
        self.label3_9 = QtWidgets.QLabel(self.videoframe_4)
        self.label3_9.setGeometry(QtCore.QRect(70, 730, 320, 180))
        self.label3_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label3_9.setText("")
        self.label3_9.setObjectName("label3_9")
        self.label3_10 = QtWidgets.QLabel(self.videoframe_4)
        self.label3_10.setGeometry(QtCore.QRect(1120, 730, 320, 180))
        self.label3_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label3_10.setText("")
        self.label3_10.setObjectName("label3_10")
        self.label3_11 = QtWidgets.QLabel(self.videoframe_4)
        self.label3_11.setGeometry(QtCore.QRect(420, 730, 320, 180))
        self.label3_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label3_11.setText("")
        self.label3_11.setObjectName("label3_11")
        self.num0_8 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num0_8.setGeometry(QtCore.QRect(200, 200, 61, 23))
        self.num0_8.setObjectName("num0_8")
        self.num0_9 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num0_9.setGeometry(QtCore.QRect(550, 200, 61, 23))
        self.num0_9.setObjectName("num0_9")
        self.num0_10 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num0_10.setGeometry(QtCore.QRect(900, 200, 61, 23))
        self.num0_10.setObjectName("num0_10")
        self.num0_11 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num0_11.setGeometry(QtCore.QRect(1250, 200, 61, 23))
        self.num0_11.setObjectName("num0_11")
        self.num1_8 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num1_8.setGeometry(QtCore.QRect(1250, 440, 61, 23))
        self.num1_8.setObjectName("num1_8")
        self.num1_9 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num1_9.setGeometry(QtCore.QRect(200, 440, 61, 23))
        self.num1_9.setObjectName("num1_9")
        self.num1_10 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num1_10.setGeometry(QtCore.QRect(550, 440, 61, 23))
        self.num1_10.setObjectName("num1_10")
        self.num1_11 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num1_11.setGeometry(QtCore.QRect(900, 440, 61, 23))
        self.num1_11.setObjectName("num1_11")
        self.num2_8 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num2_8.setGeometry(QtCore.QRect(550, 680, 61, 23))
        self.num2_8.setObjectName("num2_8")
        self.num2_9 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num2_9.setGeometry(QtCore.QRect(200, 680, 61, 23))
        self.num2_9.setObjectName("num2_9")
        self.num2_10 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num2_10.setGeometry(QtCore.QRect(900, 680, 61, 23))
        self.num2_10.setObjectName("num2_10")
        self.num2_11 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num2_11.setGeometry(QtCore.QRect(1250, 680, 61, 23))
        self.num2_11.setObjectName("num2_11")
        self.num3_8 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num3_8.setGeometry(QtCore.QRect(900, 920, 61, 23))
        self.num3_8.setObjectName("num3_8")
        self.num3_9 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num3_9.setGeometry(QtCore.QRect(550, 920, 61, 23))
        self.num3_9.setObjectName("num3_9")
        self.num3_10 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num3_10.setGeometry(QtCore.QRect(1250, 920, 61, 23))
        self.num3_10.setObjectName("num3_10")
        self.num3_11 = QtWidgets.QLCDNumber(self.videoframe_4)
        self.num3_11.setGeometry(QtCore.QRect(200, 920, 61, 23))
        self.num3_11.setObjectName("num3_11")
        self.scrubframe_4 = QtWidgets.QFrame(self.dataframe_2)
        self.scrubframe_4.setGeometry(QtCore.QRect(1540, 0, 81, 1001))
        self.scrubframe_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrubframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe_4.setObjectName("scrubframe_4")
        self.verticalSlider_3 = QtWidgets.QSlider(self.scrubframe_4)
        self.verticalSlider_3.setGeometry(QtCore.QRect(20, 10, 22, 951))
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setInvertedAppearance(True)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.maintabWidget.addTab(self.gallerypage, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.maintabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vision Data Management"))
        self.browseButton.setText(_translate("MainWindow", "..."))
        self.webcamButton.setText(_translate("MainWindow", "WebCam"))
        self.retinaButton.setText(_translate("MainWindow", "Retina"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.mainpage), _translate("MainWindow", "Main"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.gallerypage), _translate("MainWindow", "Gallery"))

