# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonframe = QtWidgets.QFrame(self.centralwidget)
        self.buttonframe.setGeometry(QtCore.QRect(1630, 0, 271, 1021))
        self.buttonframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonframe.setObjectName("buttonframe")
        self.browseButton = QtWidgets.QPushButton(self.buttonframe)
        self.browseButton.setGeometry(QtCore.QRect(20, 10, 89, 31))
        self.browseButton.setObjectName("browseButton")
        self.webcamButton = QtWidgets.QPushButton(self.buttonframe)
        self.webcamButton.setGeometry(QtCore.QRect(20, 50, 89, 31))
        self.webcamButton.setCheckable(True)
        self.webcamButton.setChecked(False)
        self.webcamButton.setAutoRepeat(False)
        self.webcamButton.setDefault(False)
        self.webcamButton.setObjectName("webcamButton")
        self.retinaButton = QtWidgets.QCheckBox(self.buttonframe)
        self.retinaButton.setGeometry(QtCore.QRect(150, 50, 89, 31))
        self.retinaButton.setObjectName("retinaButton")
        self.metadata = QtWidgets.QTableView(self.buttonframe)
        self.metadata.setGeometry(QtCore.QRect(20, 271, 211, 191))
        self.metadata.setAlternatingRowColors(True)
        self.metadata.setShowGrid(False)
        self.metadata.setGridStyle(QtCore.Qt.SolidLine)
        self.metadata.setWordWrap(True)
        self.metadata.setCornerButtonEnabled(False)
        self.metadata.setObjectName("metadata")
        self.metadata.horizontalHeader().setVisible(False)
        self.metadata.verticalHeader().setVisible(False)
        self.browseFolderButton = QtWidgets.QPushButton(self.buttonframe)
        self.browseFolderButton.setGeometry(QtCore.QRect(150, 10, 89, 31))
        self.browseFolderButton.setObjectName("browseFolderButton")
        self.deleteButton = QtWidgets.QPushButton(self.buttonframe)
        self.deleteButton.setGeometry(QtCore.QRect(20, 470, 89, 31))
        self.deleteButton.setObjectName("deleteButton")
        self.saveButton = QtWidgets.QPushButton(self.buttonframe)
        self.saveButton.setGeometry(QtCore.QRect(150, 470, 89, 31))
        self.saveButton.setObjectName("saveButton")
        self.exportButton = QtWidgets.QPushButton(self.buttonframe)
        self.exportButton.setGeometry(QtCore.QRect(60, 930, 151, 31))
        self.exportButton.setObjectName("exportButton")
        self.infoLabel = QtWidgets.QLabel(self.buttonframe)
        self.infoLabel.setGeometry(QtCore.QRect(20, 170, 211, 51))
        self.infoLabel.setText("")
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.generateButton = QtWidgets.QPushButton(self.buttonframe)
        self.generateButton.setEnabled(False)
        self.generateButton.setGeometry(QtCore.QRect(20, 110, 211, 31))
        self.generateButton.setCheckable(False)
        self.generateButton.setChecked(False)
        self.generateButton.setAutoRepeat(False)
        self.generateButton.setDefault(False)
        self.generateButton.setObjectName("generateButton")
        self.maintabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.maintabWidget.setGeometry(QtCore.QRect(10, 0, 1611, 1021))
        self.maintabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.maintabWidget.setObjectName("maintabWidget")
        self.mainpage = QtWidgets.QWidget()
        self.mainpage.setObjectName("mainpage")
        self.dataframe = QtWidgets.QFrame(self.mainpage)
        self.dataframe.setGeometry(QtCore.QRect(0, 0, 1611, 1011))
        self.dataframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataframe.setObjectName("dataframe")
        self.videoframe = QtWidgets.QFrame(self.dataframe)
        self.videoframe.setGeometry(QtCore.QRect(10, 0, 1601, 851))
        self.videoframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe.setObjectName("videoframe")
        self.label = QtWidgets.QLabel(self.videoframe)
        self.label.setGeometry(QtCore.QRect(560, 30, 480, 360))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.focallabel = QtWidgets.QLabel(self.videoframe)
        self.focallabel.setGeometry(QtCore.QRect(200, 430, 480, 360))
        self.focallabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.focallabel.setText("")
        self.focallabel.setObjectName("focallabel")
        self.corticallabel = QtWidgets.QLabel(self.videoframe)
        self.corticallabel.setGeometry(QtCore.QRect(930, 430, 480, 360))
        self.corticallabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.corticallabel.setText("")
        self.corticallabel.setObjectName("corticallabel")
        self.scrubframe = QtWidgets.QFrame(self.dataframe)
        self.scrubframe.setGeometry(QtCore.QRect(0, 850, 1611, 151))
        self.scrubframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrubframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe.setObjectName("scrubframe")
        self.scrubSlider = QtWidgets.QSlider(self.scrubframe)
        self.scrubSlider.setGeometry(QtCore.QRect(19, 10, 1531, 22))
        self.scrubSlider.setTracking(False)
        self.scrubSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scrubSlider.setObjectName("scrubSlider")
        self.frameNum = QtWidgets.QLCDNumber(self.scrubframe)
        self.frameNum.setGeometry(QtCore.QRect(1560, 10, 31, 23))
        self.frameNum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameNum.setSmallDecimalPoint(False)
        self.frameNum.setDigitCount(4)
        self.frameNum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.frameNum.setObjectName("frameNum")
        self.pauseButton = QtWidgets.QPushButton(self.scrubframe)
        self.pauseButton.setGeometry(QtCore.QRect(830, 40, 89, 29))
        self.pauseButton.setCheckable(False)
        self.pauseButton.setObjectName("pauseButton")
        self.startButton = QtWidgets.QPushButton(self.scrubframe)
        self.startButton.setGeometry(QtCore.QRect(730, 40, 89, 29))
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.skipBackButton = QtWidgets.QToolButton(self.scrubframe)
        self.skipBackButton.setGeometry(QtCore.QRect(630, 40, 89, 25))
        self.skipBackButton.setArrowType(QtCore.Qt.LeftArrow)
        self.skipBackButton.setObjectName("skipBackButton")
        self.skipForwardButton = QtWidgets.QToolButton(self.scrubframe)
        self.skipForwardButton.setGeometry(QtCore.QRect(930, 40, 89, 25))
        self.skipForwardButton.setArrowType(QtCore.Qt.RightArrow)
        self.skipForwardButton.setObjectName("skipForwardButton")
        self.maintabWidget.addTab(self.mainpage, "")
        self.focuspage = QtWidgets.QWidget()
        self.focuspage.setObjectName("focuspage")
        self.biglabel = QtWidgets.QLabel(self.focuspage)
        self.biglabel.setGeometry(QtCore.QRect(160, 80, 1280, 720))
        self.biglabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.biglabel.setText("")
        self.biglabel.setObjectName("biglabel")
        self.scrubframe_2 = QtWidgets.QFrame(self.focuspage)
        self.scrubframe_2.setGeometry(QtCore.QRect(0, 850, 1611, 161))
        self.scrubframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrubframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe_2.setObjectName("scrubframe_2")
        self.scrubSlider_2 = QtWidgets.QSlider(self.scrubframe_2)
        self.scrubSlider_2.setGeometry(QtCore.QRect(19, 10, 1531, 22))
        self.scrubSlider_2.setTracking(False)
        self.scrubSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.scrubSlider_2.setObjectName("scrubSlider_2")
        self.frameNum_2 = QtWidgets.QLCDNumber(self.scrubframe_2)
        self.frameNum_2.setGeometry(QtCore.QRect(1560, 10, 31, 23))
        self.frameNum_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameNum_2.setSmallDecimalPoint(False)
        self.frameNum_2.setDigitCount(4)
        self.frameNum_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.frameNum_2.setObjectName("frameNum_2")
        self.pauseButton_2 = QtWidgets.QPushButton(self.scrubframe_2)
        self.pauseButton_2.setGeometry(QtCore.QRect(830, 40, 89, 29))
        self.pauseButton_2.setCheckable(False)
        self.pauseButton_2.setObjectName("pauseButton_2")
        self.startButton_2 = QtWidgets.QPushButton(self.scrubframe_2)
        self.startButton_2.setGeometry(QtCore.QRect(730, 40, 89, 29))
        self.startButton_2.setCheckable(False)
        self.startButton_2.setObjectName("startButton_2")
        self.skipBackButton_2 = QtWidgets.QToolButton(self.scrubframe_2)
        self.skipBackButton_2.setGeometry(QtCore.QRect(630, 40, 89, 25))
        self.skipBackButton_2.setArrowType(QtCore.Qt.LeftArrow)
        self.skipBackButton_2.setObjectName("skipBackButton_2")
        self.skipForwardButton_2 = QtWidgets.QToolButton(self.scrubframe_2)
        self.skipForwardButton_2.setGeometry(QtCore.QRect(930, 40, 89, 25))
        self.skipForwardButton_2.setArrowType(QtCore.Qt.RightArrow)
        self.skipForwardButton_2.setObjectName("skipForwardButton_2")
        self.maintabWidget.addTab(self.focuspage, "")
        self.gallerypage = QtWidgets.QWidget()
        self.gallerypage.setObjectName("gallerypage")
        self.dataframe_2 = QtWidgets.QFrame(self.gallerypage)
        self.dataframe_2.setGeometry(QtCore.QRect(0, 0, 1621, 1011))
        self.dataframe_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataframe_2.setObjectName("dataframe_2")
        self.videoframe_4 = QtWidgets.QFrame(self.dataframe_2)
        self.videoframe_4.setGeometry(QtCore.QRect(10, 0, 1531, 1001))
        self.videoframe_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe_4.setObjectName("videoframe_4")
        self.a = ClickLabel(self.videoframe_4)
        self.a.setGeometry(QtCore.QRect(70, 10, 320, 180))
        self.a.setFocusPolicy(QtCore.Qt.NoFocus)
        self.a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.a.setText("")
        self.a.setObjectName("a")
        self.b = ClickLabel(self.videoframe_4)
        self.b.setGeometry(QtCore.QRect(420, 10, 320, 180))
        self.b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b.setText("")
        self.b.setObjectName("b")
        self.c = ClickLabel(self.videoframe_4)
        self.c.setGeometry(QtCore.QRect(770, 10, 320, 180))
        self.c.setFocusPolicy(QtCore.Qt.NoFocus)
        self.c.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c.setText("")
        self.c.setObjectName("c")
        self.d = ClickLabel(self.videoframe_4)
        self.d.setGeometry(QtCore.QRect(1120, 10, 320, 180))
        self.d.setFocusPolicy(QtCore.Qt.NoFocus)
        self.d.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.d.setText("")
        self.d.setObjectName("d")
        self.g = ClickLabel(self.videoframe_4)
        self.g.setGeometry(QtCore.QRect(770, 250, 320, 180))
        self.g.setFocusPolicy(QtCore.Qt.NoFocus)
        self.g.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.g.setText("")
        self.g.setObjectName("g")
        self.h = ClickLabel(self.videoframe_4)
        self.h.setGeometry(QtCore.QRect(1120, 250, 320, 180))
        self.h.setFocusPolicy(QtCore.Qt.NoFocus)
        self.h.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.h.setText("")
        self.h.setObjectName("h")
        self.e = ClickLabel(self.videoframe_4)
        self.e.setGeometry(QtCore.QRect(70, 250, 320, 180))
        self.e.setFocusPolicy(QtCore.Qt.NoFocus)
        self.e.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.e.setText("")
        self.e.setObjectName("e")
        self.f = ClickLabel(self.videoframe_4)
        self.f.setGeometry(QtCore.QRect(420, 250, 320, 180))
        self.f.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f.setText("")
        self.f.setObjectName("f")
        self.l = ClickLabel(self.videoframe_4)
        self.l.setGeometry(QtCore.QRect(1120, 490, 320, 180))
        self.l.setFocusPolicy(QtCore.Qt.NoFocus)
        self.l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.l.setText("")
        self.l.setObjectName("l")
        self.i = ClickLabel(self.videoframe_4)
        self.i.setGeometry(QtCore.QRect(70, 490, 320, 180))
        self.i.setFocusPolicy(QtCore.Qt.NoFocus)
        self.i.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.i.setText("")
        self.i.setObjectName("i")
        self.k = ClickLabel(self.videoframe_4)
        self.k.setGeometry(QtCore.QRect(770, 490, 320, 180))
        self.k.setFocusPolicy(QtCore.Qt.NoFocus)
        self.k.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.k.setText("")
        self.k.setObjectName("k")
        self.j = ClickLabel(self.videoframe_4)
        self.j.setGeometry(QtCore.QRect(420, 490, 320, 180))
        self.j.setFocusPolicy(QtCore.Qt.NoFocus)
        self.j.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.j.setText("")
        self.j.setObjectName("j")
        self.o = ClickLabel(self.videoframe_4)
        self.o.setGeometry(QtCore.QRect(770, 730, 320, 180))
        self.o.setFocusPolicy(QtCore.Qt.NoFocus)
        self.o.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.o.setText("")
        self.o.setObjectName("o")
        self.m = ClickLabel(self.videoframe_4)
        self.m.setGeometry(QtCore.QRect(70, 730, 320, 180))
        self.m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.m.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.m.setText("")
        self.m.setObjectName("m")
        self.p = ClickLabel(self.videoframe_4)
        self.p.setGeometry(QtCore.QRect(1120, 730, 320, 180))
        self.p.setFocusPolicy(QtCore.Qt.NoFocus)
        self.p.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p.setText("")
        self.p.setObjectName("p")
        self.n = ClickLabel(self.videoframe_4)
        self.n.setGeometry(QtCore.QRect(420, 730, 320, 180))
        self.n.setFocusPolicy(QtCore.Qt.NoFocus)
        self.n.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.n.setText("")
        self.n.setObjectName("n")
        self.numa = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numa.setGeometry(QtCore.QRect(200, 200, 61, 23))
        self.numa.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numa.setObjectName("numa")
        self.numb = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numb.setGeometry(QtCore.QRect(550, 200, 61, 23))
        self.numb.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numb.setObjectName("numb")
        self.numc = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numc.setGeometry(QtCore.QRect(900, 200, 61, 23))
        self.numc.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numc.setObjectName("numc")
        self.numd = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numd.setGeometry(QtCore.QRect(1250, 200, 61, 23))
        self.numd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numd.setObjectName("numd")
        self.numh = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numh.setGeometry(QtCore.QRect(1250, 440, 61, 23))
        self.numh.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numh.setObjectName("numh")
        self.nume = QtWidgets.QLCDNumber(self.videoframe_4)
        self.nume.setGeometry(QtCore.QRect(200, 440, 61, 23))
        self.nume.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nume.setObjectName("nume")
        self.numf = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numf.setGeometry(QtCore.QRect(550, 440, 61, 23))
        self.numf.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numf.setObjectName("numf")
        self.numg = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numg.setGeometry(QtCore.QRect(900, 440, 61, 23))
        self.numg.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numg.setObjectName("numg")
        self.numj = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numj.setGeometry(QtCore.QRect(550, 680, 61, 23))
        self.numj.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numj.setObjectName("numj")
        self.numi = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numi.setGeometry(QtCore.QRect(200, 680, 61, 23))
        self.numi.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numi.setObjectName("numi")
        self.numk = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numk.setGeometry(QtCore.QRect(900, 680, 61, 23))
        self.numk.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numk.setObjectName("numk")
        self.numl = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numl.setGeometry(QtCore.QRect(1250, 680, 61, 23))
        self.numl.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numl.setObjectName("numl")
        self.numo = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numo.setGeometry(QtCore.QRect(900, 920, 61, 23))
        self.numo.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numo.setObjectName("numo")
        self.numn = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numn.setGeometry(QtCore.QRect(550, 920, 61, 23))
        self.numn.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numn.setObjectName("numn")
        self.nump = QtWidgets.QLCDNumber(self.videoframe_4)
        self.nump.setGeometry(QtCore.QRect(1250, 920, 61, 23))
        self.nump.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nump.setObjectName("nump")
        self.numm = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numm.setGeometry(QtCore.QRect(200, 920, 61, 23))
        self.numm.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numm.setObjectName("numm")
        self.scrubframe_4 = QtWidgets.QFrame(self.dataframe_2)
        self.scrubframe_4.setGeometry(QtCore.QRect(1540, 0, 81, 1001))
        self.scrubframe_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrubframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe_4.setObjectName("scrubframe_4")
        self.verticalSlider_3 = QtWidgets.QSlider(self.scrubframe_4)
        self.verticalSlider_3.setGeometry(QtCore.QRect(20, 10, 22, 951))
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setInvertedAppearance(True)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.maintabWidget.addTab(self.gallerypage, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionDelete_Selection = QtWidgets.QAction(MainWindow)
        self.actionDelete_Selection.setObjectName("actionDelete_Selection")
        self.menuOpen.addAction(self.actionFile)
        self.menuOpen.addAction(self.actionFolder)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDelete_Selection)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.maintabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vision Data Management"))
        self.browseButton.setText(_translate("MainWindow", "Open File"))
        self.webcamButton.setText(_translate("MainWindow", "WebCam"))
        self.retinaButton.setText(_translate("MainWindow", "Retina"))
        self.browseFolderButton.setText(_translate("MainWindow", "Open Folder"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.exportButton.setText(_translate("MainWindow", "Export as..."))
        self.generateButton.setText(_translate("MainWindow", "Generate images from video"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.startButton.setText(_translate("MainWindow", "Play"))
        self.skipBackButton.setText(_translate("MainWindow", "..."))
        self.skipForwardButton.setText(_translate("MainWindow", "..."))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.mainpage), _translate("MainWindow", "Webcam"))
        self.pauseButton_2.setText(_translate("MainWindow", "Pause"))
        self.startButton_2.setText(_translate("MainWindow", "Play"))
        self.skipBackButton_2.setText(_translate("MainWindow", "..."))
        self.skipForwardButton_2.setText(_translate("MainWindow", "..."))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.focuspage), _translate("MainWindow", "Main"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.gallerypage), _translate("MainWindow", "Gallery"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionFolder.setText(_translate("MainWindow", "Folder"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionDelete_Selection.setText(_translate("MainWindow", "Delete"))

from customwidgets import ClickLabel
